name: GITHUB CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    uses: Sakonyama-Store/org_actions/.github/workflows/java-springboot-ci.yml@main
    with:
      java-version: '11'
    secrets: inherit



